-- Año: 2024
-- Grupo Nro:
-- Integrantes: Grellet Martinoia, Alejandro // Sanchez Mateo 
-- Tema: AGROSA
-- Nombre del Esquema (LBD02024G()AGROSA)
-- Plataforma Windows 10 // Docker Buildx (Docker Inc., v0.9.1) :
-- Motor y Versión: MySQL SServer 8.0.36
-- GitHub Repositorio: LBD2024G04
-- GitHub Usuario: AlejandroGrellet // Mateo-Sanchez14
CREATE SCHEMA IF NOT EXISTS `LBD2024G()AGROSA` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `LBD2024G()AGROSA`.`USURAIOS` (
  `idUSUARIOS` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `tipoUsuario` ENUM('Administrador', 'Secretario') DEFAULT 'Secretario' NOT NULL,
  `estado` BINARY(1) NOT NULL,
  PRIMARY KEY (`idUSUARIOS`),
  UNIQUE INDEX `idUsuario_UNIQUE` (`idUSUARIOS` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LBD2024G()AGROSA`.`RUBROS` (
  `idRUBROS` INT(11) NOT NULL AUTO_INCREMENT,
  `rubro` VARCHAR(45) NOT NULL,
  `tipoRubro` ENUM('Egreso', 'Ingreso') NOT NULL,
  `estado` CHAR(1) NOT NULL,
  PRIMARY KEY (`idRUBROS`),
  UNIQUE INDEX `idRUBROS_UNIQUE` (`idRUBROS` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LBD2024G()AGROSA`.`MOVIMIENTOS` (
  `idMOVIMIENTOS` INT(11) NOT NULL,
  `tipoMovimiento` CHAR(1) NOT NULL,
  `fecha` DATE NOT NULL,
  `monto` DECIMAL NOT NULL,
  `detalle` VARCHAR(80) NULL DEFAULT NULL,
  `estado` CHAR(1) NOT NULL,
  `idRUBROS` INT(11) NOT NULL,
  PRIMARY KEY (`idMOVIMIENTOS`, `tipoMovimiento`, `idRUBROS`),
  UNIQUE INDEX `idMOVIMIENTOS_UNIQUE` (`idMOVIMIENTOS` ASC) VISIBLE,
  INDEX `fk_MOVIMIENTOS_RUBROS_idx` (`idRUBROS` ASC) VISIBLE,
  CONSTRAINT Check_Montos CHECK (`tipoMovimiento`= "E" AND `monto` <=0 OR `tipoMovimiento`= "I" AND `monto` >=0 ),
  CONSTRAINT `fk_MOVIMIENTOS_RUBROS`
    FOREIGN KEY (`idRUBROS`)
    REFERENCES `LBD2024G()AGROSA`.`RUBROS` (`idRUBROS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
  
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LBD2024G()AGROSA`.`EMPLEADOS` (
  `idEMPLEADO` INT(11) NOT NULL,
  `cuil` INT(11) UNSIGNED NOT NULL,
  `nombres` VARCHAR(30) NOT NULL,
  `apellidos` VARCHAR(30) NOT NULL,
  `estado` CHAR(1) NOT NULL,
  PRIMARY KEY (`idEMPLEADO`),
  UNIQUE INDEX `idEMPLEADOS_UNIQUE` (`idEMPLEADO` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LBD2024G()AGROSA`.`FINCAS` (
  `idFINCA` INT(11) NOT NULL,
  `finca` VARCHAR(45) NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `cuilResoinsable` INT(11) NOT NULL,
  `latitud` FLOAT(11) NULL DEFAULT NULL,
  `longitud` FLOAT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idFINCA`),
  UNIQUE INDEX `idFINCAS_UNIQUE` (`idFINCA` ASC) VISIBLE,
  UNIQUE INDEX `longitud_UNIQUE` (`longitud` ASC) VISIBLE,
  UNIQUE INDEX `latitud_UNIQUE` (`latitud` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LBD2024G()AGROSA`.`PARTES` (
  `idPARTE` INT(11) NOT NULL,
  `fechaParte` DATE NOT NULL,
  `estado` CHAR(1) NOT NULL,
  `superficie` FLOAT(11) NOT NULL,
  `idENCARGADO` INT(11) NOT NULL,
  `idFINCA` INT(11) NOT NULL,
  PRIMARY KEY (`idPARTE`),
  UNIQUE INDEX `idPARTES_UNIQUE` (`idPARTE` ASC) VISIBLE,
  INDEX `fk_PARTES_EMPLEADOS1_idx` (`idENCARGADO` ASC) VISIBLE,
  INDEX `fk_PARTES_FINCAS1_idx` (`idFINCA` ASC) VISIBLE,
  CONSTRAINT `fk_PARTES_EMPLEADOS1`
    FOREIGN KEY (`idENCARGADO`)
    REFERENCES `LBD2024G()AGROSA`.`EMPLEADOS` (`idEMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTES_FINCAS1`
    FOREIGN KEY (`idFINCA`)
    REFERENCES `LBD2024G()AGROSA`.`FINCAS` (`idFINCA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `LBD2024G()AGROSA`.`LINEAS_PARTES` (
  `idPARTE` INT(11) NOT NULL,
  `idEMPLEADO` INT(11) NOT NULL,
  `rol` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`idPARTE`, `idEMPLEADO`),
  INDEX `fk_PARTES_has_EMPLEADOS_EMPLEADOS1_idx` (`idEMPLEADO` ASC) VISIBLE,
  INDEX `fk_PARTES_has_EMPLEADOS_PARTES1_idx` (`idPARTE` ASC) VISIBLE,
  CONSTRAINT `fk_PARTES_has_EMPLEADOS_PARTES1`
    FOREIGN KEY (`idPARTE`)
    REFERENCES `LBD2024G()AGROSA`.`PARTES` (`idPARTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PARTES_has_EMPLEADOS_EMPLEADOS1`
    FOREIGN KEY (`idEMPLEADO`)
    REFERENCES `LBD2024G()AGROSA`.`EMPLEADOS` (`idEMPLEADO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;