name: Linter

on:
  pull_request:
    branches:
      - main

jobs:
  lint-client:
    name: 🔦 Linting SQL
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Install linter
        run: pip install sqlfluff
      - name: Run lint
        run: sqlfluff lint --dialect mysql